language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - npm install -g coveralls
script:
   - make ci
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info | coveralls
notifications:
  irc: "chat.freenode.net#brass-monkey"